from .login import Ui_Fenetrelogin
from .absence import Ui_recapabsentFenetre
from .ajoutcours import Ui_AjoutNouveauCours
from .cours import Ui_FenetreCours
from .detaiscours import Ui_Form
from .enregistrerseance import Ui_enregistrerseancefenetre
from .inscrireetudiant import Ui_insciptionEtudiants
from .listeetudiants import Ui_listedesetudiants
from .newuser import Ui_UserinscriptionFenetre
from .prochaineseance import Ui_prochaineseancesFenetre
from .seance import Ui_seanceFenetre
